### PR TITLE
#1: Add User Roles

### PR DESCRIPTION
**Pull request by timmatussek**
This PR adds a role for each user for each course iteration the user is in.
The added roles for now are "student", "corrector", "admin".
A function "get-user-role" to get the role by user-id and course-iteration-id has been added to db.clj.
Schema, specs and dummy data have been updated to contain the roles.

### CODE REVIEW

**Review by matlorr — CHANGES_REQUESTED** [review]
Looks good to me so far :D.
I think it would be nice to have a :distinct keyword 
in the :user/roles definition to enforce the fact that
users cannot have different roles in the same 
course-iteration.

**Comment by timmatussek** [comment]
@matlorr Thanks for the feedback. I cannot find any mention of :distinct in the spectomic docs. It also appears that we dont use this anywhere else in our codebase yet, so im a bit unsure how this would work. Could you please link the docs to it?

**Review by MarkusBott — COMMENTED** [review]
seems fine

**Comment by matlorr** [comment]
After further discussion it was concluded that a validation of roles should be performed
on the controller level.

**Review by matlorr — APPROVED** [review]
LGTM

**Comment by MarkusBott** [comment]
> LGTM

**Pull request merged**
